# Publish GitHub workflow artifacts tutorial example
name: Generate & Publish Mail Signatures

on:
  push:
    branches: [ main ]

jobs:
       
  generate_publish_mail_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: Generate signatures
        run: ./generate_signatures.sh   
      - uses: ChanTsune/release-with-commit@v2.8.0
        with:
          regexp: "Release ((\\d+([.]\\d+)*)-(alpha|beta|rc)\\d*)((\\s|\\S)*)"
          regexp_options: "us"
          release_name: "version $1"
          tag_name: "v$1"
          body: "$5"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' # This token is provided by Actions, you do not need to create your own token
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: signatures/**