# Publish GitHub workflow artifacts tutorial example
name: Generate & Publish Mail Signatures

on:
  push:
    branches: [ main ]

jobs:
       
  generate_publish_mail_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: Generate signatures
        run: ./generate_signatures.sh    
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: signatures/**