# Publish GitHub workflow artifacts tutorial example
name: Generate & Publish Mail Signatures

on:
  push:
    branches: [ main ]

jobs:
       
  generate_publish_mail_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: Generate signatures
        run: ./generate_signatures.sh   
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "Organisation e-mail signatures"
          files: |
            signatures/**